version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: go-chat
    ports:
      - "3306:3306"
    volumes:
      - /workspaces/mysql:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /workspaces/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /workspaces/go-chat/web/dist:/usr/share/nginx/html
      - /workspaces/nginx/logs:/var/log/nginx
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
